# Generated by Django 3.2.11 on 2022-04-30 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LocationLow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('thetao', models.FloatField()),
                ('date', models.DateField()),
                ('fishing', models.BooleanField()),
            ],
        ),
    ]
