# Generated by Django 3.2.11 on 2022-05-10 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemperatureLow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('thetao', models.FloatField()),
                ('date', models.DateField()),
                ('fishing', models.BooleanField()),
            ],
        ),
    ]
