# Generated by Django 3.2.11 on 2022-05-10 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_temperaturelow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationlow',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='temperaturelow',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
