# Generated by Django 3.2.11 on 2022-05-11 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20220510_1844'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentLow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('uo', models.FloatField()),
                ('vo', models.FloatField()),
                ('date', models.DateTimeField()),
                ('fishing', models.BooleanField()),
            ],
        ),
    ]
