# Generated by Django 3.2.11 on 2022-05-12 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_currentlow'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChlorophylLow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('chl', models.FloatField()),
                ('date', models.DateTimeField()),
                ('fishing', models.BooleanField()),
            ],
        ),
    ]
